import { describe, expect, it } from "vitest";

import { fnv1a } from "#/lib/flywheel-alert";

// The flywheel baseline compares this Worker's hashes against a manifest generated by
// ml/train.py (`_fnv1a`). If the two implementations ever diverge, every label reads as
// "changed" and the retrain email fires spuriously — so pin the well-known FNV-1a/32 vectors.
describe("fnv1a", () => {
	it("matches canonical FNV-1a 32-bit test vectors (== ml/train.py)", () => {
		expect(fnv1a("")).toBe(2166136261); // offset basis
		expect(fnv1a("a")).toBe(0xe40c292c);
		expect(fnv1a("foobar")).toBe(0xbf9cf968);
	});

	it("returns an unsigned 32-bit int", () => {
		const h = fnv1a('{"inner":[[0.1,0.2]],"outer":[[0.0,0.0]]}');
		expect(h).toBeGreaterThanOrEqual(0);
		expect(h).toBeLessThanOrEqual(0xffffffff);
		expect(Number.isInteger(h)).toBe(true);
	});
});
