/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiRecordsRouteImport } from './routes/api/records'
import { Route as AdminCaptureRouteImport } from './routes/admin/capture'
import { Route as ApiPhotosSplatRouteImport } from './routes/api/photos.$'
import { Route as ApiCronDigestRouteImport } from './routes/api/cron.digest'
import { Route as AdminRecordsNewRouteImport } from './routes/admin/records.new'
import { Route as AdminRecordsIdEditRouteImport } from './routes/admin/records.$id.edit'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRecordsRoute = ApiRecordsRouteImport.update({
  id: '/api/records',
  path: '/api/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCaptureRoute = AdminCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPhotosSplatRoute = ApiPhotosSplatRouteImport.update({
  id: '/api/photos/$',
  path: '/api/photos/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDigestRoute = ApiCronDigestRouteImport.update({
  id: '/api/cron/digest',
  path: '/api/cron/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecordsNewRoute = AdminRecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRecordsIdEditRoute = AdminRecordsIdEditRouteImport.update({
  id: '/records/$id/edit',
  path: '/records/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/capture': typeof AdminCaptureRoute
  '/api/records': typeof ApiRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
  '/admin/records/$id/edit': typeof AdminRecordsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/capture': typeof AdminCaptureRoute
  '/api/records': typeof ApiRecordsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
  '/admin/records/$id/edit': typeof AdminRecordsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/capture': typeof AdminCaptureRoute
  '/api/records': typeof ApiRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
  '/admin/records/$id/edit': typeof AdminRecordsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/capture'
    | '/api/records'
    | '/admin/'
    | '/admin/records/new'
    | '/api/cron/digest'
    | '/api/photos/$'
    | '/admin/records/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/capture'
    | '/api/records'
    | '/admin'
    | '/admin/records/new'
    | '/api/cron/digest'
    | '/api/photos/$'
    | '/admin/records/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/capture'
    | '/api/records'
    | '/admin/'
    | '/admin/records/new'
    | '/api/cron/digest'
    | '/api/photos/$'
    | '/admin/records/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiRecordsRoute: typeof ApiRecordsRoute
  ApiCronDigestRoute: typeof ApiCronDigestRoute
  ApiPhotosSplatRoute: typeof ApiPhotosSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/records': {
      id: '/api/records'
      path: '/api/records'
      fullPath: '/api/records'
      preLoaderRoute: typeof ApiRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/capture': {
      id: '/admin/capture'
      path: '/capture'
      fullPath: '/admin/capture'
      preLoaderRoute: typeof AdminCaptureRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/photos/$': {
      id: '/api/photos/$'
      path: '/api/photos/$'
      fullPath: '/api/photos/$'
      preLoaderRoute: typeof ApiPhotosSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/digest': {
      id: '/api/cron/digest'
      path: '/api/cron/digest'
      fullPath: '/api/cron/digest'
      preLoaderRoute: typeof ApiCronDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/records/new': {
      id: '/admin/records/new'
      path: '/records/new'
      fullPath: '/admin/records/new'
      preLoaderRoute: typeof AdminRecordsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/records/$id/edit': {
      id: '/admin/records/$id/edit'
      path: '/records/$id/edit'
      fullPath: '/admin/records/$id/edit'
      preLoaderRoute: typeof AdminRecordsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCaptureRoute: typeof AdminCaptureRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRecordsNewRoute: typeof AdminRecordsNewRoute
  AdminRecordsIdEditRoute: typeof AdminRecordsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCaptureRoute: AdminCaptureRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRecordsNewRoute: AdminRecordsNewRoute,
  AdminRecordsIdEditRoute: AdminRecordsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiRecordsRoute: ApiRecordsRoute,
  ApiCronDigestRoute: ApiCronDigestRoute,
  ApiPhotosSplatRoute: ApiPhotosSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
