/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiRecordsRouteImport } from './routes/api/records'
import { Route as AdminRecordsNewRouteImport } from './routes/admin/records.new'
import { Route as AdminRecordsIdEditRouteImport } from './routes/admin/records.$id.edit'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRecordsRoute = ApiRecordsRouteImport.update({
  id: '/api/records',
  path: '/api/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecordsNewRoute = AdminRecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRecordsIdEditRoute = AdminRecordsIdEditRouteImport.update({
  id: '/records/$id/edit',
  path: '/records/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/api/records': typeof ApiRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/admin/records/$id/edit': typeof AdminRecordsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/api/records': typeof ApiRecordsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/admin/records/$id/edit': typeof AdminRecordsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/api/records': typeof ApiRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/admin/records/$id/edit': typeof AdminRecordsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mcp'
    | '/api/records'
    | '/admin/'
    | '/admin/records/new'
    | '/admin/records/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/api/records'
    | '/admin'
    | '/admin/records/new'
    | '/admin/records/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mcp'
    | '/api/records'
    | '/admin/'
    | '/admin/records/new'
    | '/admin/records/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  McpRoute: typeof McpRoute
  ApiRecordsRoute: typeof ApiRecordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/records': {
      id: '/api/records'
      path: '/api/records'
      fullPath: '/api/records'
      preLoaderRoute: typeof ApiRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/records/new': {
      id: '/admin/records/new'
      path: '/records/new'
      fullPath: '/admin/records/new'
      preLoaderRoute: typeof AdminRecordsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/records/$id/edit': {
      id: '/admin/records/$id/edit'
      path: '/records/$id/edit'
      fullPath: '/admin/records/$id/edit'
      preLoaderRoute: typeof AdminRecordsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRecordsNewRoute: typeof AdminRecordsNewRoute
  AdminRecordsIdEditRoute: typeof AdminRecordsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminRecordsNewRoute: AdminRecordsNewRoute,
  AdminRecordsIdEditRoute: AdminRecordsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  McpRoute: McpRoute,
  ApiRecordsRoute: ApiRecordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
