/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CollectionRouteRouteImport } from './routes/_collection/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CollectionIndexRouteImport } from './routes/_collection/index'
import { Route as ApiRecordsRouteImport } from './routes/api/records'
import { Route as AdminCaptureRouteImport } from './routes/admin/capture'
import { Route as ApiPhotosSplatRouteImport } from './routes/api/photos.$'
import { Route as ApiDiscogsCoverIdRouteImport } from './routes/api/discogs-cover.$id'
import { Route as ApiCronDigestRouteImport } from './routes/api/cron.digest'
import { Route as ApiAdminBackupRouteImport } from './routes/api/admin/backup'
import { Route as AdminRecordsNewRouteImport } from './routes/admin/records.new'
import { Route as AdminRecordsIdRouteImport } from './routes/admin/records.$id'
import { Route as CollectionRecordsIdRouteImport } from './routes/_collection/records.$id'

const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRouteRoute = CollectionRouteRouteImport.update({
  id: '/_collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRouteRoute,
} as any)
const ApiRecordsRoute = ApiRecordsRouteImport.update({
  id: '/api/records',
  path: '/api/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCaptureRoute = AdminCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPhotosSplatRoute = ApiPhotosSplatRouteImport.update({
  id: '/api/photos/$',
  path: '/api/photos/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscogsCoverIdRoute = ApiDiscogsCoverIdRouteImport.update({
  id: '/api/discogs-cover/$id',
  path: '/api/discogs-cover/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDigestRoute = ApiCronDigestRouteImport.update({
  id: '/api/cron/digest',
  path: '/api/cron/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBackupRoute = ApiAdminBackupRouteImport.update({
  id: '/api/admin/backup',
  path: '/api/admin/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecordsNewRoute = AdminRecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRecordsIdRoute = AdminRecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CollectionRecordsIdRoute = CollectionRecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => CollectionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CollectionIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/admin/capture': typeof AdminCaptureRoute
  '/api/records': typeof ApiRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/records/$id': typeof CollectionRecordsIdRoute
  '/admin/records/$id': typeof AdminRecordsIdRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/api/admin/backup': typeof ApiAdminBackupRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/discogs-cover/$id': typeof ApiDiscogsCoverIdRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/admin/capture': typeof AdminCaptureRoute
  '/api/records': typeof ApiRecordsRoute
  '/': typeof CollectionIndexRoute
  '/admin': typeof AdminIndexRoute
  '/records/$id': typeof CollectionRecordsIdRoute
  '/admin/records/$id': typeof AdminRecordsIdRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/api/admin/backup': typeof ApiAdminBackupRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/discogs-cover/$id': typeof ApiDiscogsCoverIdRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_collection': typeof CollectionRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/admin/capture': typeof AdminCaptureRoute
  '/api/records': typeof ApiRecordsRoute
  '/_collection/': typeof CollectionIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_collection/records/$id': typeof CollectionRecordsIdRoute
  '/admin/records/$id': typeof AdminRecordsIdRoute
  '/admin/records/new': typeof AdminRecordsNewRoute
  '/api/admin/backup': typeof ApiAdminBackupRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/discogs-cover/$id': typeof ApiDiscogsCoverIdRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/404'
    | '/500'
    | '/admin/capture'
    | '/api/records'
    | '/admin/'
    | '/records/$id'
    | '/admin/records/$id'
    | '/admin/records/new'
    | '/api/admin/backup'
    | '/api/cron/digest'
    | '/api/discogs-cover/$id'
    | '/api/photos/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/500'
    | '/admin/capture'
    | '/api/records'
    | '/'
    | '/admin'
    | '/records/$id'
    | '/admin/records/$id'
    | '/admin/records/new'
    | '/api/admin/backup'
    | '/api/cron/digest'
    | '/api/discogs-cover/$id'
    | '/api/photos/$'
  id:
    | '__root__'
    | '/_collection'
    | '/admin'
    | '/404'
    | '/500'
    | '/admin/capture'
    | '/api/records'
    | '/_collection/'
    | '/admin/'
    | '/_collection/records/$id'
    | '/admin/records/$id'
    | '/admin/records/new'
    | '/api/admin/backup'
    | '/api/cron/digest'
    | '/api/discogs-cover/$id'
    | '/api/photos/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CollectionRouteRoute: typeof CollectionRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  ApiRecordsRoute: typeof ApiRecordsRoute
  ApiAdminBackupRoute: typeof ApiAdminBackupRoute
  ApiCronDigestRoute: typeof ApiCronDigestRoute
  ApiDiscogsCoverIdRoute: typeof ApiDiscogsCoverIdRoute
  ApiPhotosSplatRoute: typeof ApiPhotosSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_collection': {
      id: '/_collection'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CollectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_collection/': {
      id: '/_collection/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRouteRoute
    }
    '/api/records': {
      id: '/api/records'
      path: '/api/records'
      fullPath: '/api/records'
      preLoaderRoute: typeof ApiRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/capture': {
      id: '/admin/capture'
      path: '/capture'
      fullPath: '/admin/capture'
      preLoaderRoute: typeof AdminCaptureRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/photos/$': {
      id: '/api/photos/$'
      path: '/api/photos/$'
      fullPath: '/api/photos/$'
      preLoaderRoute: typeof ApiPhotosSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discogs-cover/$id': {
      id: '/api/discogs-cover/$id'
      path: '/api/discogs-cover/$id'
      fullPath: '/api/discogs-cover/$id'
      preLoaderRoute: typeof ApiDiscogsCoverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/digest': {
      id: '/api/cron/digest'
      path: '/api/cron/digest'
      fullPath: '/api/cron/digest'
      preLoaderRoute: typeof ApiCronDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/backup': {
      id: '/api/admin/backup'
      path: '/api/admin/backup'
      fullPath: '/api/admin/backup'
      preLoaderRoute: typeof ApiAdminBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/records/new': {
      id: '/admin/records/new'
      path: '/records/new'
      fullPath: '/admin/records/new'
      preLoaderRoute: typeof AdminRecordsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/records/$id': {
      id: '/admin/records/$id'
      path: '/records/$id'
      fullPath: '/admin/records/$id'
      preLoaderRoute: typeof AdminRecordsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_collection/records/$id': {
      id: '/_collection/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof CollectionRecordsIdRouteImport
      parentRoute: typeof CollectionRouteRoute
    }
  }
}

interface CollectionRouteRouteChildren {
  CollectionIndexRoute: typeof CollectionIndexRoute
  CollectionRecordsIdRoute: typeof CollectionRecordsIdRoute
}

const CollectionRouteRouteChildren: CollectionRouteRouteChildren = {
  CollectionIndexRoute: CollectionIndexRoute,
  CollectionRecordsIdRoute: CollectionRecordsIdRoute,
}

const CollectionRouteRouteWithChildren = CollectionRouteRoute._addFileChildren(
  CollectionRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCaptureRoute: typeof AdminCaptureRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRecordsIdRoute: typeof AdminRecordsIdRoute
  AdminRecordsNewRoute: typeof AdminRecordsNewRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCaptureRoute: AdminCaptureRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRecordsIdRoute: AdminRecordsIdRoute,
  AdminRecordsNewRoute: AdminRecordsNewRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CollectionRouteRoute: CollectionRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  R404Route: R404Route,
  R500Route: R500Route,
  ApiRecordsRoute: ApiRecordsRoute,
  ApiAdminBackupRoute: ApiAdminBackupRoute,
  ApiCronDigestRoute: ApiCronDigestRoute,
  ApiDiscogsCoverIdRoute: ApiDiscogsCoverIdRoute,
  ApiPhotosSplatRoute: ApiPhotosSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
